/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package server;

/**
 *
 * @author Admin
 */
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import user.UserClient;
import user.userLogin;

public class wsServer extends javax.swing.JFrame {

    private static final int SERVER_PORT = 9090;
    private static final String SERVER_IP = "127.0.0.1";
    private static String check;
    private static final ExecutorService pool = Executors.newFixedThreadPool(50);
    private static String username;
    private static String password;
    private static ArrayList<clientHandler> clients  = new ArrayList();

    /**
     * Creates new form wsServer
     */
    public wsServer() {
        initComponents();
    }
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wsServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wsServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wsServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wsServer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wsServer().setVisible(true);
            }
        });

        ServerSocket listener = new ServerSocket(SERVER_PORT);

        while (true) {
            System.out.println("[SERVER]  Waiting...");
            Socket client = listener.accept();
            System.out.println("[SERVER] Connected to client");
            System.out.println(client);
            clientHandler clientThread = new clientHandler(client, clients);
            pool.execute(clientThread);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JBPowerDown1 = new javax.swing.JButton();
        JBPowerDown = new javax.swing.JButton();
        JTFUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JPFPassword = new javax.swing.JPasswordField();
        JBSignIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMIN USER");

        jPanel1.setBackground(new java.awt.Color(0, 240, 120));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );

        JBPowerDown1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBPowerDown1.setText("RESTART");
        JBPowerDown1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPowerDown1ActionPerformed(evt);
            }
        });

        JBPowerDown.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JBPowerDown.setText("POWER DOWN");
        JBPowerDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBPowerDownActionPerformed(evt);
            }
        });

        JTFUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFUsernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PASSWORD");
        jLabel2.setToolTipText("");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JPFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPFPasswordActionPerformed(evt);
            }
        });

        JBSignIn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JBSignIn.setText("SIGN IN");
        JBSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBSignInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(JBPowerDown1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JBPowerDown))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JTFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(41, 41, 41)
                            .addComponent(JBSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(JBPowerDown, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JBPowerDown1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTFUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPFPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JBSignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBPowerDown1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPowerDown1ActionPerformed
        // TODO add your handling code here:
        JTFUsername.setText(null);
        JPFPassword.setText(null);
    }//GEN-LAST:event_JBPowerDown1ActionPerformed

    private void JBPowerDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBPowerDownActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBPowerDownActionPerformed

    private void JTFUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFUsernameActionPerformed

    private void JBSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBSignInActionPerformed

        username = JTFUsername.getText();
        password = JPFPassword.getText();
        if (username.equals("") || password.equals("")) {
            JOptionPane.showMessageDialog(null, "Invalid Login Details", "login Error", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                signin(username, password);
            } catch (IOException ex) {
                Logger.getLogger(userLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JBSignInActionPerformed

    private void JPFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPFPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JPFPasswordActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBPowerDown;
    private javax.swing.JButton JBPowerDown1;
    private javax.swing.JButton JBSignIn;
    private javax.swing.JPasswordField JPFPassword;
    private javax.swing.JTextField JTFUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    
    private void signin(String Username, String Password) throws IOException {
                String message = null;        
        try {
            FileReader fin = new FileReader("adminLogin.txt");
            BufferedReader din = new BufferedReader(fin);
            //read from the file
            String line = null; // line of text
            int checker = 0;
            while ((line = din.readLine()) != null) {
                StringTokenizer st = new StringTokenizer(line, ":");
                String AUsername = st.nextToken().trim();
                String APassword = st.nextToken().trim();
                if (Password.equals(APassword) && Username.equals(AUsername)) {
                    JOptionPane.showMessageDialog(null, "Login Success","Login",JOptionPane.INFORMATION_MESSAGE);
                    checker = 1;
                    wsPage info = new wsPage();
                    info.setVisible(true);
                }
            }

            if (checker == 0) {
                JOptionPane.showMessageDialog(null, "Invalid Login Details","login Error",JOptionPane.ERROR_MESSAGE);
            }
            din.close(); // close the stream
        } catch (IOException e) {
            System.err.println("Error! - " + e.getMessage());
        }
    }
}
